Replace omitProps with omit add unit tests stories
appnexus/lucid pull request #1337
Opened 2022-03-08 23:59 UTC by yasskin

## PR Checklist

Description of changes:
For the Tag component:
- Replaces omitProps method with _.omit and explicit list of props
- Adds unit tests to make sure correct props are being omitted or passed on
- Upgrades Tag stories to be functional and use controls
- Adds descriptions to the Tag stories

Link(s) to Storybook on docspot:
https://docspot.adnxs.net/projects/lucid/CXP-2588-Replace-omitProps-in-Tag/?path=/docs/communication-tag--basic

- Manually tested across supported browsers

  - [x] Chrome
  - [ ] Firefox
  - [ ] Safari

- [ ] Two core team engineer approvals
- [ ] One core team UX approval (as necessary)
- [x] Unit tests written (`common` at minimum)
- [x] PR has one of the `semver-` labels

2022-03-09 00:45 UTC, dreidn approved these changes

2022-03-09 14:06 UTC, tsantef requested changes
Use expect over assert

2022-03-11 18:39 UTC, jhaage approved these changes

2022-03-11 19:12 UTC, lennoxdavidjr approved these changes

2022-03-11 19:36 UTC, merged